from pathlib import Path

# ----- Edamam API -----
# URL endpoint
EDAMAM_URL = "https://api.edamam.com/api/food-database/v2/parser"

# ----- Weight Estimation Constants -----
# Image size for a camera distance of 20cm from the item
IMAGE_HEIGHT = 30
IMAGE_WIDTH = 22

# Factor to approximate filling of the visual area of food in %
AREA_FILL = 0.7

# Average depth of food in cm
DEPTH_DICT = {
    "omelette": 1.0,
    "burger": 5.0,
    "pizza": 1.0,
    "fries": 3.0,
    "bread": 1.5,
    "salad": 3.0,
}

# Density values in g/ccm
DENSITY_DICT = {
    "omelette": 0.8,
    "burger": 0.7,
    "pizza": 0.675,
    "fries": 0.25,
    "bread": 0.2,
    "salad": 0.68,
}

# ----- YOLO Model -----
MODEL_VERSION = Path("model.pt")
MODEL_THRESHOLD = 0.7

# ----- Vision API -----
# Food items we are considering
VALID_ITEMS = [
    "Burger",
    "Hamburger",
    "Pizza",
    "Pizza Margherita",
    "Chesse burger",
    "Cheese Burger",
    "Dried Fruit",
    "Acai",
    "Apple",
    "Apricot",
    "Avocado",
    "Banana",
    "Blackberries",
    "Blood Oranges",
    "Blueberries",
    "Cantaloupe",
    "Cherries",
    "Clementine",
    "Dates",
    "Figs",
    "Fruit salad",
    "Grapes",
    "Jackfruit",
    "Kiwi",
    "Lemon",
    "Lime",
    "Lychees",
    "Mandarin Oranges",
    "Mango",
    "Mulberries",
    "Nectarine",
    "Olives",
    "Orange",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Pear",
    "Physalis",
    "Pineapple",
    "Plantains",
    "Plum",
    "Pomegranate",
    "Quince",
    "Raisins",
    "Raspberries",
    "Rhubarb",
    "Starfruit",
    "Strawberries",
    "Tangerine",
    "Watermelon",
    "Avocado",
    "Banana",
    "Cantaloupe Melon",
    "Casaba Melon",
    "Cherimoya",
    "Dragon Fruit",
    "Durian",
    "Galia Melon",
    "Grapefruit",
    "Guava",
    "Honeydew",
    "Jackfruit",
    "Kiwi",
    "Mandarin Oranges",
    "Mango",
    "Mangosteen",
    "Maracuya",
    "Maraschino Cherries",
    "Muskmelon",
    "Passion Fruit",
    "Pineapple",
    "Pink Grapefruit",
    "Plantain",
    "Pomegranate",
    "Star Fruit",
    "Watermelon",
    "Baked Potato",
    "Boiled Potatoes",
    "Cassava",
    "Croquettes",
    "Dumplings",
    "French Fries",
    "Fried Potatoes",
    "Gnocchi",
    "Marrow Dumplings",
    "Mashed Potatoes",
    "Omelette",
    "Potato",
    "Potato Dumpling",
    "Potato Fritter",
    "Potato Gratin",
    "Potato Pancakes",
    "Potato Salad",
    "Potato Wedges",
    "Red Potatoes",
    "Roast Potatoes",
    "Rosemary Potatoes",
    "Rösti",
    "Russet Potatoes",
    "Sweet Potato",
    "Artichoke",
    "Asparagus",
    "Aubergine",
    "Beetroot",
    "Bell Pepper",
    "Black Olives",
    "Broccoli",
    "Brussels Sprouts",
    "Cabbage",
    "Capsicum",
    "Carrot",
    "Cauliflower",
    "Celery",
    "Chard",
    "Cherry Tomato",
    "Chicory",
    "Chinese Cabbage",
    "Chives",
    "Collard Greens",
    "Corn",
    "Courgette",
    "Creamed Spinach",
    "Cucumber",
    "Eggplant",
    "Endive",
    "Fennel",
    "Garlic",
    "Gherkin",
    "Gourd",
    "Green Beans",
    "Green Olives",
    "Green Onion",
    "Horseradish",
    "Kale",
    "Kohlrabi",
    "Kumara",
    "Leek",
    "Lettuce",
    "Mushrooms",
    "Mustard Greens",
    "Olives",
    "Onion",
    "Parsnips",
    "Peas",
    "Pepper",
    "Potato",
    "Pumpkin",
    "Radishes",
    "Red Cabbage",
    "Rutabaga",
    "Shallots",
    "Spinach",
    "Squash",
    "Sweet Potato",
    "Tomato",
    "Turnip Greens",
    "Turnips",
    "Wasabi",
    "Winter Squash",
    "Zucchini",
    "BBQ Rib",
    "Bean Burrito",
    "Bratwurst",
    "Cheeseburger",
    "Chicken Breast",
    "Chicken Fajita",
    "Chicken Nuggets",
    "Chicken Sandwich",
    "Chicken Wings",
    "Curly Fries",
    "Double Cheeseburger",
    "Egg Roll",
    "Falafel",
    "Fish and Chips",
    "French Fries",
    "Grilled Chicken Salad",
    "Ham Sandwich",
    "Hamburger",
    "Hot Dog",
    "Lasagna",
    "Nachos with Cheese",
    "Onion Rings",
    "Smoked Salmon",
    "Tortilla Wrap",
    "Tuna",
    "Turkey",
    "Veggie Burger",
    "BBQ Chicken Pizza",
    "BBQ Pizza",
    "Beef Pizza",
    "Bianca Pizza",
    "Buffalo Chicken Pizza",
    "Calabrese Pizza",
    "Calzone",
    "Capricciosa Pizza",
    "Cheese Pizza",
    "Chicken Pizza",
    "Four Cheese Pizza",
    "Goat Cheese Pizza",
    "Grilled Pizza",
    "Hawaiian Pizza",
    "Margherita Pizza",
    "Mozzarella Pizza",
    "Mushroom Pizza",
    "Napoli Pizza",
    "New York Style Pizza",
    "Pepperoni Pizza",
    "Quattro Formaggi Pizza",
    "Red Pepper Pizza",
    "Salami Pizza",
    "Sausage Pizza",
    "Seafood Pizza",
    "Shrimp Pizza",
    "Sicilian Pizza",
    "Spinach Feta Pizza",
    "Spinach Pizza",
    "Stuffed Crust Pizza",
    "Tuna Pizza",
    "Vegetable Pizza",
    "Vegetarian Pizza",
    "Veggie Pizza",
    "White Pizza",
    "Babybel",
    "Blue Cheese",
    "Brie",
    "Camembert",
    "Cheddar",
    "Cheese Fondue",
    "Cheese Spread",
    "Chester",
    "Colby Cheese",
    "Colby-Jack Cheese",
    "Cottage Cheese",
    "Dutch Cheese",
    "Edam Cheese",
    "Emmentaler",
    "Feta",
    "Fontina",
    "Fresh Mozzarella",
    "Goat Cheese",
    "Gorgonzola",
    "Gouda",
    "Grated Parmesan",
    "Grilled Cheese",
    "Gruyere",
    "Halloumi",
    "Havarti",
    "Italian Cheese",
    "Jarlsberg",
    "Manchego Cheese",
    "Monterey",
    "Monterey Jack Cheese",
    "Mozzarella",
    "Muenster Cheese",
    "Neufchatel",
    "Parmesan",
    "Pecorino",
    "Provolone",
    "Raclette Cheese",
    "Ricotta",
    "White Cheddar",
    "Wisconsin Cheese",
    "Chive Cream Cheese",
    "Cottage Cheese",
    "Cream Cheese",
    "Cream Cheese with Herbs",
    "Feta Cream Cheese",
    "Garlic Cream Cheese",
    "Goat Cheese",
    "Horseradish",
    "Mascarpone",
    "Obatzda",
    "Olive Cream Cheese",
    "Pesto Cream Cheese",
    "Philadelphia Cream Cheese",
    "Pineapple Cream Cheese",
    "Salmon Cream Cheese",
    "Vegetable Cream Cheese",
    "Walnut Cream Cheese",
    "Almond Milk",
    "Buttermilk",
    "Chocolate Mousse",
    "Coconut Milk",
    "Condensed Milk",
    "Cottage Cheese",
    "Cream",
    "Creme Fraiche",
    "Custard",
    "Evaporated Milk",
    "Goat Milk",
    "Hot Chocolate",
    "Kefir",
    "Lactose-free Milk",
    "Lassi",
    "Milk",
    "Plain Yogurt",
    "Powdered Milk",
    "Quark",
    "Rice Milk",
    "Rice Pudding",
    "Semi-skimmed Milk",
    "Semolina Pudding",
    "Skim Milk",
    "Sour Cream",
    "Soy Milk",
    "Sweetened Condensed Milk",
    "Tzatziki",
    "Whipped Cream",
    "Whole Milk",
    "Yogurt",
    "American Cheese",
    "Bergkäse",
    "Butter Cheese",
    "Cheddar",
    "Emmentaler",
    "Fresh Mozzarella",
    "Gouda",
    "Gouda Cheese",
    "Havarti",
    "Leerdammer",
    "Leerdammer Cheese",
    "Maasdam Cheese",
    "Monterey Jack Cheese",
    "Mozzarella",
    "Muenster Cheese",
    "Pepper Cheese",
    "Smoked Cheese",
    "Tilsit",
    "White Cheddar",
    "Young Gouda",
    "Aloe Vera Yogurt",
    "Ayran",
    "Bircher Muesli Yogurt",
    "Blueberry Yogurt",
    "Cherry Yogurt",
    "Chocolate Yogurt",
    "Cream Yogurt",
    "Creamy Yogurt",
    "Diet Yogurt",
    "Fruit Yogurt",
    "Greek Yogurt",
    "Low-Fat Yogurt",
    "Mocca Yogurt",
    "Organic Yogurt",
    "Peach Yogurt",
    "Plain Yogurt",
    "Probiotic Yogurt",
    "Skim Milk Yogurt",
    "Stracciatella Yogurt",
    "Strawberry Yogurt",
    "Vanilla Yogurt",
    "Yogurt",
    "Yogurt Corner",
    "Beef Brisket",
    "Beef Fillet",
    "Beef Goulash",
    "Beef Minute Steak",
    "Beef Neck",
    "Beef Pancreas",
    "Beef Patty",
    "Beef Prime Rib",
    "Beef Ribs",
    "Beef Sirloin",
    "Beef Suet",
    "Beef Tallow",
    "Beef Thymus",
    "Beef Tripe",
    "Chuck Roast",
    "Chuck Steak",
    "Filet Mignon",
    "Flank Steak",
    "Minced Veal",
    "Porterhouse Steak",
    "Rib Eye Steak",
    "Roast Beef",
    "Rump Steak",
    "Skirt Steak",
    "Stew Beef",
    "Strip Steak",
    "T-Bone-Steak",
    "Veal Breast",
    "Veal Leg",
    "Veal Roast Beef",
    "Veal Shank",
    "Veal Shoulder",
    "Veal Sirloin",
    "Veal Tenderloin",
    "Baked Ham",
    "Beef Salami",
    "Boiled Ham",
    "Bologna",
    "Bresaola",
    "Capicola",
    "Chicken Breast Fillet",
    "Chopped Ham",
    "Chorizo",
    "Corned Beef",
    "Dutch Loaf",
    "Ham",
    "Ham Sausage",
    "Hickory Ham",
    "Honey Ham",
    "Liverwurst",
    "Olive Loaf",
    "Oven-Roasted Turkey Breast",
    "Parma Ham",
    "Pastrami",
    "Pepperoni",
    "Pimento Loaf",
    "Pork Roast",
    "Prosciutto",
    "Roast Beef",
    "Salami",
    "Serrano Ham",
    "Smoked Ham",
    "Smoked Turkey Breast",
    "Summer Sausage",
    "Turkey Breast",
    "Turkey Ham",
    "Turkey Salami",
    "Beef",
    "Beef Brisket",
    "Beef Jerky",
    "Beef Ribs",
    "Beef Tenderloin",
    "Chicken",
    "Chicken Breast",
    "Chicken Leg",
    "Chicken Liver",
    "Chicken Meat",
    "Chicken Thigh",
    "Chicken Wing",
    "Duck",
    "Filet Mignon",
    "Flank Steak",
    "Flat Iron Steak",
    "Ham",
    "New York Strip Steak",
    "Ostrich",
    "Pork",
    "Pork Baby Back Ribs",
    "Pork Chops",
    "Pork Country-Style Ribs",
    "Pork Loin",
    "Pork Roast",
    "Pork Steaks",
    "Roast Beef",
    "Round Steak",
    "Schnitzel",
    "Spare Ribs",
    "Standing Rib Roast",
    "T-Bone Steak",
    "Turkey",
    "Turkey Breast",
    "Turkey Legs",
    "Turkey Steak",
    "Turkey Wings",
    "Chicken Giblets",
    "Chicken Heart",
    "Chicken Liver",
    "Chicken Stomach",
    "Chitterlings",
    "Duck Liver",
    "Goose Liver",
    "Hog Maws",
    "Pig Heart",
    "Pig Kidney",
    "Pork Liver",
    "Pork Melt",
    "Pork Tongue",
    "Turkey Giblets",
    "Turkey Heart",
    "Turkey Liver",
    "Veal Heart",
    "Veal Kidney",
    "Veal Tongue",
    "Bacon",
    "Canadian-Style Bacon",
    "Chitterlings",
    "Ground Pork",
    "Hog Maws",
    "Lard",
    "Meatloaf",
    "Parma Ham",
    "Pig Ear",
    "Pork Bacon",
    "Pork Belly",
    "Pork Blade Steak",
    "Pork Chop",
    "Pork Country-Style Ribs",
    "Pork Crown Roast",
    "Pork Cutlet",
    "Pork Cutlets",
    "Pork Loin",
    "Pork Meatloaf",
    "Pork Ragout",
    "Pork Rib Roast",
    "Pork Ribs",
    "Pork Roast",
    "Pork Sausage",
    "Pork Shank",
    "Pork Shoulder",
    "Pork Shoulder Blade",
    "Pork Stomach",
    "Serrano Ham",
    "Spare Ribs",
    "Spareribs",
    "Capon",
    "Chicken",
    "Chicken Breast",
    "Chicken Drumsticks",
    "Chicken Gizzards",
    "Chicken Legs",
    "Chicken Thighs",
    "Chicken Wings",
    "Duck",
    "Duck Breast",
    "Emu",
    "Goose",
    "Guinea-Fowl",
    "Ostrich",
    "Ostrich Meat",
    "Pheasant",
    "Pheasant Breast",
    "Pheasant Leg",
    "Pigeon",
    "Poularde",
    "Rhea",
    "Turkey",
    "Turkey Breast",
    "Turkey Cutlet",
    "Turkey Drumsticks",
    "Turkey Legs",
    "Turkey Steak",
    "Turkey Wings",
    "Wild Duck",
    "Andouille",
    "Bacon",
    "Black Pudding",
    "Blood Sausage",
    "Bockwurst",
    "Boiled Ham",
    "Bologna",
    "Boudin",
    "Bratwurst",
    "Brawn",
    "Breakfast Sausage Links",
    "Cheese Pastry",
    "Chicken Breast",
    "Chicken Meat",
    "Chicken Salad",
    "Chorizo",
    "Cooked Ham",
    "Corned Beef",
    "Cumberland Sausage",
    "Frankfurters",
    "Garlic Sausage",
    "Hot Dogs",
    "Hot Sausage",
    "Italian Sausage",
    "Jerky",
    "Kielbasa",
    "Knackwurst",
    "Landjaeger",
    "Linguica",
    "Liver Pate",
    "Liverwurst",
    "Mortadella",
    "Pastrami",
    "Pepperoni",
    "Polish Sausage",
    "Pork",
    "Pork Roll",
    "Prosciutto",
    "Salami",
    "Sausage",
    "Weisswurst",
    "Lamb",
    "Lamb Meat",
    "Moose",
    "Moose Meat",
    "Mutton",
    "Mutton Meat",
    "Rabbit",
    "Reindeer",
    "Reindeer Meat",
    "Venison",
    "Venison Sirloin",
    "Wild Boar",
    "Apple Cake",
    "Apple Crumble",
    "Apple Pie",
    "Apple Strudel",
    "Apple Turnover",
    "Black Forest Cake",
    "Blueberry Cobbler",
    "Blueberry Muffin",
    "Blueberry Pie",
    "Caramel Cake",
    "Carrot Cake",
    "Cheesecake",
    "Cherry Pie",
    "Chocolate Cake",
    "Chocolate Cream Pie",
    "Chocolate Mousse Cake",
    "Chocolate Mousse Pie",
    "Chocolate Muffin",
    "Coconut Cake",
    "Cupcake",
    "Danish Pastry",
    "Donut",
    "Doughnut",
    "Flourless Chocolate Cake",
    "German Chocolate Cake",
    "Gingerbread",
    "Ice Cream Cake",
    "Key Lime Pie",
    "King Cake",
    "Lemon Cake",
    "Lemon Meringue Pie",
    "Madeira Cake",
    "Marble Cake",
    "Meringue",
    "Opera Cake",
    "Paczki",
    "Pancake",
    "Panettone",
    "Pavlova",
    "Peach Cobbler",
    "Peach Pie",
    "Pecan Pie",
    "Pineapple Upside-Down Cake",
    "Plum Cake",
    "Poppy-Seed Cake",
    "Pound Cake",
    "Profiterole",
    "Puff Pastry",
    "Pumpkin Bread",
    "Pumpkin Cheesecake",
    "Pumpkin Pie",
    "Raspberry Pie",
    "Red Velvet Cake",
    "Rhubarb Pie",
    "Rum Cake",
    "Sacher Torte",
    "Sponge Cake",
    "Strawberry Cheesecake",
    "Strawberry Pie",
    "Strawberry Rhubarb Pie",
    "Sweet Potato Pie",
    "Tarte Tatin",
    "Tiramisu",
    "Tiramisu Cake",
    "Treacle Tart",
    "Tres Leches Cake",
    "Trifle",
    "Victoria Sponge Cake",
    "Waffles",
    "Wedding Cake",
    "Airheads",
    "Almond Roca",
    "Angel Delight",
    "Animal Crackers",
    "Baby Ruth",
    "Butterfinger",
    "Buttermilk Pancakes",
    "Caramel Popcorn",
    "Caramel squares",
    "Chocolate",
    "Chocolate Bar",
    "Chocolate Chips",
    "Cookies",
    "Cotton Candy",
    "Eggy Bread",
    "Fairy Cakes",
    "Liquorice",
    "Lollipop",
    "Marshmallows",
    "Marzipan",
    "Mike and Ike",
    "Milk Duds",
    "PayDay",
    "Peanut Bar",
    "Peanut Brittle",
    "Peanut Butter Bars",
    "Peanut Butter Cookies",
    "Peppermint bark",
    "Popcorn",
    "Pumpkin Seeds",
    "Reeses Peanut Butter Cups",
    "Rice Pudding",
    "Roasted Almonds",
    "Rolo",
    "Semolina",
    "Waffles",
    "Whoopie Pie",
    "Baskin-Robbins",
    "Butter Pecan Ice Cream",
    "Carvel",
    "Chocolate Chip Ice Cream",
    "Chocolate Ice Cream",
    "Coffee Ice Cream",
    "Cold Stone Creamery",
    "Cookie Dough Ice Cream",
    "Dippin Dots",
    "Double Rainbow",
    "Drumsticks",
    "French Vanilla Ice Cream",
    "Healthy Choice",
    "Hot Fudge Sundae",
    "Ice Cream Sandwich",
    "Ice Cream Sundae",
    "Ice Milk",
    "Magnolia",
    "Strawberry Ice Cream",
    "Strawberry Sundae",
    "Sundae",
    "Turkey Hill",
    "Vanilla Cone",
    "Vanilla Ice Cream",
    "Aloe Vera",
    "Apple Juice",
    "Apricot Nectar",
    "Banana Juice",
    "Blackberry Juice",
    "Boysenberry Juice",
    "Capri-Sun",
    "Carrot Juice",
    "Chamomile Tea",
    "Cherry Juice",
    "Clamato",
    "Coconut Milk",
    "Coconut Water",
    "Concord Grape",
    "Cranberry Apple Juice",
    "Cranberry Grape Juice",
    "Cranberry Juice",
    "Cucumber Juice",
    "Currant Juice",
    "Energy-Drink",
    "Fruitopia",
    "Grape Juice",
    "Grapefruit Juice",
    "Lemon Juice",
    "Lemonade",
    "Lime Juice",
    "Limeade",
    "Mango Lassi",
    "Orange Juice",
    "Papaya Juice",
    "Passion Fruit Juice",
    "Peach Juice",
    "Peach Nectar",
    "Pear Juice",
    "Pear Nectar",
    "Pineapple Juice",
    "Pineapple Orange Juice",
    "Plum Juice",
    "Pomegranate Juice",
    "Sauerkraut Juice",
    "Tangerine Juice",
    "Tomato Juice",
    "Vegetable Juice",
    "White Grape Juice",
    "Advocaat",
    "Applejack",
    "Asti",
    "Wine",
    "Beer",
    "Ginger Beer",
    "Lager Beer",
    "Non-alcoholic Beer",
    "Chai",
    "Chai Tea",
    "Chocolate Milk",
    "Chocolate Milkshake",
    "Club Mate",
    "Coca Cola",
    "Coffee",
    "Coke Zero",
    "Cola",
    "Crystal Light",
    "Diet Coke",
    "Egg Cream",
    "Egg Nog",
    "Elderflower Cordial",
    "Evian",
    "Gatorade",
    "Ginger Tea",
    "Hawaiian Punch",
    "Hi-C",
    "Horchata",
    "Hot Chocolate",
    "Ice Tea",
    "Iced Tea",
    "Karamalz",
    "Kombucha",
    "Kool-Aid",
    "Lassi",
    "Latte Macchiato",
    "Lemonade",
    "Malt Beer",
    "Milk",
    "Milkshake (dry)",
    "Milo",
    "Nectar",
    "Nestea",
    "Non-alcoholic Beer",
    "Powerade",
    "Slurpee",
    "Slush Puppie",
    "Smoothie",
    "Soy Milk",
    "Strawberry Milkshake",
    "Tang",
    "Tap Water",
    "Tea",
    "Vanilla Milkshake",
    "Volvic",
    "Water",
    "Yerba Mate",
    "7up",
    "Barq’s",
    "Bitter Lemon",
    "Canada Dry Ginger Ale",
    "Cherry Coke",
    "Coke",
    "Coke Zero",
    "Diet Cherry Coke",
    "Diet Coke",
    "Diet Pepsi",
    "Fanta",
    "Fanta Zero",
    "Five Alive",
    "Fresca",
    "Full Throttle",
    "Fuze",
    "Fuze Tea",
    "Gatorade",
    "Ginger Ale",
    "Ice Tea",
    "Jolt Cola",
    "Kool-Aid",
    "Lemonade",
    "Mello Yello",
    "Powerade",
    "Schweppes Ginger Ale",
    "Soda",
    "Sprite",
    "Sprite Zero",
    "Squirt",
    "Sunkist",
    "Surge",
    "TaB",
    "Tonic Water",
    "Vanilla Coke",
    "Cabernet Sauvignon",
    "Cava",
    "Champagne",
    "Chardonnay",
    "Chenin Blanc",
    "Chocolate Wine",
    "Dry Red Wine",
    "Gamay",
    "Prosecco",
    "Red Wine",
    "Red Wines",
    "Riesling",
    "Riesling Wine",
    "Rose Wine",
    "Sangria",
    "Sauvignon Blanc",
    "Sherry",
    "Shiraz",
    "Sparkling Wine",
    "Sweet Red Wine",
    "Sweet White Wine",
    "Sweet Wines",
    "Vermouth",
    "White Wine",
    "White Zinfandel",
    "Wine",
    "Yellow Tail Wine",
    "Brown Rice",
    "Buckwheat",
    "Buckwheat Groats",
    "Corn Waffles",
    "Cornmeal",
    "Cornstarch",
    "Couscous",
    "Cracker",
    "Durum Wheat Semolina",
    "Flaxseed",
    "Oat Bran",
    "Pearl Barley",
    "Polenta",
    "Prawn Crackers",
    "Pretzel Sticks",
    "Quinoa",
    "Rye Bran",
    "Sago",
    "Savoury Biscuits",
    "Shortbread",
    "Spelt",
    "Spelt Bran",
    "Spelt Semolina",
    "Sunflower Seeds",
    "Tortilla Chips",
    "Wheat Bran",
    "Wheat Germ",
    "Wheat Gluten",
    "Wheat Semolina",
    "Wheat Starch",
    "Whole Grain Wheat",
    "Wholegrain Oat",
    "Bran Flakes",
    "Cheerios",
    "Chex",
    "Chocolate Cheerios",
    "Chocos",
    "Cinnamon Toast Crunch",
    "Coco Pops",
    "Cocoa Krispies",
    "Cocoa Pebbles",
    "Cocoa Puffs",
    "Cookie Crisp",
    "Corn Flakes",
    "Corn Pops",
    "Count Chocula",
    "Cracklin Oat Bran",
    "Cream of Wheat",
    "Crunchy Nut",
    "Crunchy Nut Cornflakes",
    "Fiber One",
    "Froot Loops",
    "Frosted Cheerios",
    "Frosted Flakes",
    "Frosted Mini-Wheats",
    "Frosties",
    "Fruity Pebbles",
    "Golden Grahams",
    "Grape-Nuts",
    "Honey Nut Cheerios",
    "Honey Smacks",
    "Honeycomb",
    "Just Right",
    "Kashi",
    "Kelloggs Corn Flakes",
    "Kix",
    "Krave",
    "Life Cereal",
    "Lucky Charms",
    "Malt-O-Meal",
    "Mini-Wheats",
    "Muesli",
    "Multigrain Cheerios",
    "Nutri-Grain",
    "Oatibix",
    "Oatmeal",
    "Post Shredded Wheat",
    "Puffed Rice",
    "Puffed Wheat",
    "Ready Brek",
    "Rice Chex",
    "Rice Krispies",
    "Scooters",
    "Shredded Wheat",
    "Shreddies",
    "Smart Start",
    "Sugar Puffs",
    "Toasties",
    "Trix",
    "Cannelloni",
    "Capellini",
    "Cappelletti",
    "Cellophane Noodles",
    "Cheese Tortellini",
    "Dampfnudel",
    "Dumpling Dough",
    "Durum Wheat Semolina",
    "Egg Noodles",
    "Farfalle",
    "Fettuccine",
    "Fusilli",
    "Glass Noodles",
    "Lasagne Sheets",
    "Linguine",
    "Low Carb Pasta",
    "Macaroni",
    "Manicotti",
    "Mostaccioli",
    "Orecchiette",
    "Orzo",
    "Penne",
    "Penne Rigate",
    "Pierogi",
    "Ravioli",
    "Rigatoni",
    "Rotini",
    "Shells",
    "Shirataki Noodles",
    "Soy Noodles",
    "Spaetzle",
    "Spaghetti",
    "Spinach Tortellini",
    "Spirelli",
    "Tagliatelle",
    "Tortellini",
    "Vermicelli",
    "Whole Grain Noodles",
    "Whole Grain Spaghetti",
    "Ziti",
    "Bacon and Eggs",
    "Baked Beans",
    "Baked Chicken",
    "BBQ Ribs",
    "Beef Stew",
    "Biryani",
    "Black Pudding",
    "Black Rice",
    "BLT",
    "Brown Rice",
    "Burrito",
    "Butter Chicken",
    "California Roll",
    "Chicken Caesar Salad",
    "Chicken Fried Steak",
    "Chicken Marsala",
    "Chicken Parmesan",
    "Chicken Pot Pie",
    "Chicken Tikka Masala",
    "Chili con Carne",
    "Chimichanga",
    "Cobb Salad",
    "Collard Greens",
    "Cottage Pie",
    "Dal",
    "Deviled Eggs",
    "Dim Sum",
    "Dosa",
    "Enchiladas",
    "Fajita",
    "Fish and Chips",
    "Fried Rice",
    "Fried Shrimp",
    "Grilled Cheese Sandwich",
    "Ham and Cheese Sandwich",
    "Hummus",
    "Jambalaya",
    "Kebab",
    "Lasagne",
    "Mac and Cheese",
    "Macaroni and Cheese",
    "Mashed Potatoes",
    "Meat Pie",
    "Meatloaf",
    "Naan",
    "Orange Chicken",
    "Pad Thai",
    "Paella",
    "Paratha",
    "Pea Soup",
    "Peanut Butter Sandwich",
    "Peking Duck",
    "Philly Cheese Steak",
    "Pizza",
    "Pork Chop",
    "Potato Salad",
    "Pulled Pork Sandwich",
    "Ramen",
    "Ravioli",
    "Reuben Sandwich",
    "Roast Beef",
    "Roast Dinner",
    "Samosa",
    "Sausage Roll",
    "Shepherds Pie",
    "Spaghetti Bolognese",
    "Spring Roll",
    "Taco",
    "Tandoori Chicken",
    "Yorkshire Pudding",
    "Alphabet Soup",
    "Bean Stew",
    "Broccoli Soup",
    "Carrot Ginger Soup",
    "Carrot Soup",
    "Chicken Vegetable Soup",
    "Chicken with Rice Soup",
    "French Onion Soup",
    "Golden Mushroom Soup",
    "Goulash",
    "Lentil Soup",
    "Lobster Bisque Soup",
    "Meatball Soup",
    "Minestrone",
    "Mushroom Soup",
    "Noodle Soup",
    "Onion Soup",
    "Oxtail Soup",
    "Pea Soup",
    "Potato Soup",
    "Pumpkin Soup",
    "Ramen",
    "Scotch Broth",
    "Succotash",
    "Thai Soup",
    "Tomato Rice Soup",
    "Tomato Soup",
    "Vegetable Beef Soup",
    "Vegetable Broth",
    "Vegetable Soup",
    "Vegetable Stock",
    "Wedding Soup",
    "Azuki Bean",
    "Bamboo Shoots",
    "Bean Curd",
    "Bean Sprouts",
    "Bengal Gram",
    "Black Beans",
    "Black Chickpeas",
    "Black Gram",
    "Brown Lentil",
    "Butternut",
    "Chickpeas",
    "Chili Bean",
    "Dal",
    "Deep-Fried Tofu",
    "Extra-Firm Tofu",
    "Firm Tofu",
    "Flageolet",
    "Fried Bean Curd",
    "Green Beans",
    "Green Gram",
    "Green Lentil",
    "Kidney Beans",
    "Lentils",
    "Lima Beans",
    "Marron",
    "Miso",
    "Mung Beans",
    "Natto",
    "Navy Bean",
    "Okara",
    "Okra",
    "Peanuts",
    "Peas",
    "Pecan",
    "Pinto Beans",
    "Puy Lentils",
    "Rajma",
    "Red Beans",
    "Red Kidney Bean",
    "Red Lentils",
    "Refried Beans",
    "Roasted Soybeans",
    "Silken Tofu",
    "Soft Tofu",
    "Soybeans",
    "Soynut Butter",
    "Sugar Peas",
    "Sweet Peas",
    "Tempeh",
    "Textured Soy Protein",
    "Textured Vegetable Protein",
    "Tofu",
    "White Beans",
    "Yam Bean",
    "Yellow Lentils",
    "Yuba",
    "Acorn",
    "Alfalfa Sprouts",
    "Almonds",
    "Beechnut",
    "Brazil Nuts",
    "Breadfruit",
    "Butternut",
    "Cashew",
    "Chestnut",
    "Chia Seeds",
    "Coconut",
    "Cotton Seeds",
    "Flaxseed",
    "Ginkgo Nuts",
    "Goa Bean",
    "Hazelnut",
    "Hickory Nuts",
    "Lima Beans",
    "Lotus Seed",
    "Macadamia Nuts",
    "Peanuts",
    "Peas",
    "Pecan Nuts",
    "Pecans",
    "Pili Nuts",
    "Pine Nuts",
    "Pinto Beans",
    "Pistachios",
    "Poppy Seeds",
    "Pumpkin Seeds",
    "Radish Seeds",
    "Safflower Seeds",
    "Sesame Seeds",
    "Smoked Almonds",
    "Soy Beans",
    "Sunflower Seeds",
    "Sweet Chestnut",
    "Walnuts",
    "Watermelon",
    "Olive Oil",
    "Almonds",
    "Apple Pie Filling",
    "Butterscotch Chips",
    "Cane Sugar",
    "Chocolate Chips",
    "Chocolate Sprinkles",
    "Cocoa Powder",
    "Coconut Flakes",
    "Coconut Milk",
    "Corn Flour",
    "Corn Syrup",
    "Cornmeal",
    "Cornstarch",
    "Couverture",
    "Cream Cheese",
    "Cream of Tartar",
    "Crystallized Ginger",
    "Custard Powder",
    "Dark Rum",
    "Dextrose",
    "Dried Apricots",
    "Dried Cranberries",
    "Dried Figs",
    "Egg",
    "Egg White",
    "Egg Yolk",
    "Evaporated Milk",
    "Flour",
    "Ground Cinnamon",
    "Hazelnuts",
    "Heavy Cream",
    "Lemon Pie Filling",
    "Maple Syrup",
    "Molasses",
    "Peppermint Extract",
    "Raisins",
    "Rolled Oats",
    "Sesame Seeds",
    "Shredded Coconut",
    "Soy Milk",
    "Sunflower Seeds",
    "Walnuts",
    "Whole Milk",
    "Anchovy",
    "Bluefish",
    "Bream",
    "Butterfish",
    "Calamari",
    "Carp",
    "Caviar",
    "Clam",
    "Cod",
    "Crawfish",
    "Flounder",
    "Grouper",
    "Haddock",
    "Hake",
    "Halibut",
    "Herring",
    "Hoki",
    "Kipper",
    "Ling",
    "Lobster",
    "Mackerel",
    "Milkfish",
    "Monkfish",
    "Mullet",
    "Mussel",
    "Octopus",
    "Pickerel",
    "Pickled Herring",
    "Pike",
    "Plaice",
    "Pollack",
    "Red Snapper",
    "Redfish",
    "Rollmops",
    "Salmon",
    "Sardines",
    "Scallops",
    "Scampi",
    "Sea Bass",
    "Squid",
    "Sturgeon",
    "Sushi",
    "Swordfish",
    "Triggerfish",
    "Trout",
    "Tuna",
    "Tuna Salad",
    "Whitefish",
    "Whiting",
    "Zander",
    "Chili",
    "Fennel",
    "Ginger",
    "Apple Pie",
    "Bagel",
    "Baguette",
    "Banana Bread",
    "Breadsticks",
    "Brioche",
    "Brown Bread",
    "Brownies",
    "Bun",
    "Cannoli",
    "Caramel Cake",
    "Challah",
    "Chapati",
    "Ciabatta",
    "Cinnamon Bun",
    "Coffee Cake",
    "Conchas/Mexican Sweet Bread",
    "Cornbread",
    "Crepes",
    "Croissant",
    "Cupcakes",
    "Donut/Doughnut",
    "Dosa",
    "Empanada",
    "English Muffin",
    "Flatbread",
    "Focaccia",
    "Garlic Bread",
    "Muffin",
    "Multi-Grain Bread",
    "Naan",
    "Oatmeal Cookies",
    "Pan de Sal",
    "Pancake",
    "Pandesal",
    "Panettone",
    "Pretzel",
    "Puff Pastry",
    "Pumpernickel",
    "Raisin Bread",
    "Roll",
    "Roti",
    "Rye Bread",
    "Sandwich",
    "Sandwich Bread",
    "Scone",
    "Shortcrust Pastry",
    "Soda Bread",
    "Soufflé",
    "Sourdough Bread",
    "Spanakopita",
    "Spice Cake",
    "Toast",
    "Tortilla",
    "Ranch Dressing",
    "Thai Curry Paste",
    "Yogurt Dressing",
    "Zesty Italian Dressing",
    "Chocolate Philadelphia",
    "Chocolate Spread",
    "Cream Cheese",
    "Egg",
    "Grape Jelly",
    "Honey",
    "Liverwurst",
    "Nutella",
]

# items for exclusion from Vision API classifications
INVALID_ITEMS = [
    "Food",
    "Fried food",
    "Finger food",
    "Deep frying",
    "Delicacy",
    "Side dish",
    "Fast food restaurant",
    "Meal",
    "Slider",
    "appetizer",
    "Brunch",
    "Red cabbage",
    "Vegan nutrition",
    "Sweetness",
    "Sourness",
    "Bitterness",
    "Green",
    "Tableware",
    "Recipe",
    "Ingredient",
    "Fast food",
    "Fruit",
    "Staple food",
    "Cooking",
    "Kitchen",
    "Cookware and bakeware",
    "Baked goods",
    "Cuisine",
    "Dish",
    "Produce",
    "Comfort food",
    "Garnish",
    "Junk Food",
    "Take-out food",
    "Italian food",
    "Meat",
    "Vegetable",
    "Plate",
    "American Food",
    "Chinese Food",
    "Food additive",
    "Serveware",
    "Supper",
    "Lunch",
    "Breakfast",
    "Gluten",
    "art",
    "Indian cuisine",
    "Natural foods",
    "Baking",
    "Leaf vegetable",
    "American food",
]
