# Edamam endpoint
EDAMAM_URL = "https://api.edamam.com/api/food-database/v2/parser"

# food items we are considering for Vision API
VALID_ITEMS = [
    "Burger",
    "Hamburger",
    "Pizza",
    "Pizza Margherita",
    "Cheese burger",
    "Cheese Burger",
    "Omelette",
]

# items for exclusion from Vision API classifications
INVALID_ITEMS = [
    "Food",
    "Fried food",
    "Finger food",
    "Deep frying",
    "Delicacy",
    "Side dish",
    "Fast food restaurant",
    "Meal",
    "Slider",
    "appetizer",
    "Brunch",
    "Red cabbage",
    "Vegan nutrition",
    "Sweetness",
    "Sourness",
    "Bitterness",
    "Green",
    "Tableware",
    "Recipe",
    "Ingredient",
    "Fast food",
    "Fruit",
    "Staple food",
    "Cooking",
    "Kitchen",
    "Cookware and bakeware",
    "Baked goods",
    "Cuisine",
    "Dish",
    "Produce",
    "Comfort food",
    "Garnish",
    "Junk Food",
    "Take-out food",
    "Italian food",
    "Meat",
    "Vegetable",
    "Plate",
    "American Food",
    "Chinese Food",
    "Food additive",
    "Serveware",
    "Supper",
    "Lunch",
    "Breakfast",
    "Gluten",
    "art",
    "Indian cuisine",
    "Natural foods",
    "Baking",
    "Leaf vegetable",
    "American food",
]
