# Edamam endpoint
EDAMAM_URL = "https://api.edamam.com/api/food-database/v2/parser"

# food items we are considering for Vision API
VALID_ITEMS = [
    "Burger",
    "Hamburger",
    "Pizza",
    "Pizza Margherita",
    "Chesse burger",
    "Cheese Burger",
    "Applesauce",
    "Dried Fruit",
    "Acai",
    "Apple",
    "Applesauce",
    "Apricot",
    "Avocado",
    "Banana",
    "Blackberries",
    "Blood Oranges",
    "Blueberries",
    "Cantaloupe",
    "Cherries",
    "Clementine",
    "Cranberries",
    "Currants",
    "Custard Apple",
    "Dates",
    "Figs",
    "Fruit salad",
    "Grapes",
    "Greengage",
    "Guava",
    "Jackfruit",
    "Kiwi",
    "Lemon",
    "Lime",
    "Lychees",
    "Mandarin Oranges",
    "Mango",
    "Minneola",
    "Mulberries",
    "Nectarine",
    "Olives",
    "Orange",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Pear",
    "Physalis",
    "Pineapple",
    "Plantains",
    "Plum",
    "Pomegranate",
    "Quince",
    "Raisins",
    "Rambutan",
    "Raspberries",
    "Rhubarb",
    "Starfruit",
    "Strawberries",
    "Tangerine",
    "Watermelon",
    "Asian Pear",
    "Avocado",
    "Banana",
    "Cantaloupe Melon",
    "Casaba Melon",
    "Cherimoya",
    "Dragon Fruit",
    "Durian",
    "Galia Melon",
    "Grapefruit",
    "Guava",
    "Honeydew",
    "Jackfruit",
    "Kiwi",
    "Lychee",
    "Mandarin Oranges",
    "Mango",
    "Mangosteen",
    "Maracuya",
    "Maraschino Cherries",
    "Muskmelon",
    "Passion Fruit",
    "Pineapple",
    "Pink Grapefruit",
    "Plantain",
    "Pomegranate",
    "Pomelo",
    "Prickly Pear",
    "Soursop Fruit",
    "Star Fruit",
    "Watermelon",
    "All-blue Potatoes",
    "Baked Potato",
    "Boiled Potatoes",
    "Cassava",
    "Croquettes",
    "Dumpling Dough",
    "Dumplings",
    "French Fingerling Potatoes",
    "French Fries",
    "Fried Potatoes",
    "Gnocchi",
    "Japanese Sweet Potatoes",
    "Marrow Dumplings",
    "Mashed Potatoes",
    "Omelette",
    "Potato",
    "Potato Dumpling",
    "Potato Fritter",
    "Potato Gratin",
    "Potato Pancakes",
    "Potato Salad",
    "Potato Starch",
    "Potato Sticks",
    "Potato Waffles",
    "Potato Wedges",
    "Red Potatoes",
    "Roast Potatoes",
    "Rosemary Potatoes",
    "Rösti",
    "Russet Potatoes",
    "Sweet Potato",
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Aubergine",
    "Beetroot",
    "Bell Pepper",
    "Black Olives",
    "Broccoli",
    "Brussels Sprouts",
    "Cabbage",
    "Capsicum",
    "Carrot",
    "Cauliflower",
    "Celery",
    "Chard",
    "Cherry Tomato",
    "Chicory",
    "Chinese Cabbage",
    "Chives",
    "Collard Greens",
    "Corn",
    "Courgette",
    "Creamed Spinach",
    "Cucumber",
    "Eggplant",
    "Endive",
    "Fennel",
    "Garlic",
    "Gherkin",
    "Gourd",
    "Green Beans",
    "Green Olives",
    "Green Onion",
    "Horseradish",
    "Kale",
    "Kohlrabi",
    "Kumara",
    "Leek",
    "Lettuce",
    "Mushrooms",
    "Mustard Greens",
    "Olives",
    "Onion",
    "Parsnips",
    "Peas",
    "Pepper",
    "Potato",
    "Pumpkin",
    "Radishes",
    "Red Cabbage",
    "Rutabaga",
    "Shallots",
    "Spinach",
    "Squash",
    "Sweet Potato",
    "Tomato",
    "Turnip Greens",
    "Turnips",
    "Wasabi",
    "Winter Squash",
    "Zucchini",
    "BBQ Rib",
    "Bean Burrito",
    "Bratwurst",
    "Cheeseburger",
    "Chicken Breast",
    "Chicken Fajita",
    "Chicken McNuggets",
    "Chicken Nuggets",
    "Chicken Pizziola",
    "Chicken Sandwich",
    "Chicken Teriyaki Sandwich",
    "Chicken Wings",
    "Chop Suey",
    "Curly Fries",
    "Double Cheeseburger",
    "Egg Roll",
    "Falafel",
    "Fish and Chips",
    "Fish Sandwich",
    "French Fries",
    "Grilled Chicken Salad",
    "Ham Sandwich",
    "Hamburger",
    "Hot Dog",
    "Italian BMT",
    "Lasagna",
    "Meatball Sandwich",
    "Nachos with Cheese",
    "Onion Rings",
    "Smoked Salmon",
    "Spicy Italian",
    "Subway Club Sandwich",
    "Tortilla Wrap",
    "Tuna",
    "Turkey",
    "Veggie Burger",
    "Veggie Patty",
    "BBQ Chicken Pizza",
    "BBQ Pizza",
    "Beef Pizza",
    "Bianca Pizza",
    "Buffalo Chicken Pizza",
    "Calabrese Pizza",
    "Calzone",
    "Capricciosa Pizza",
    "Cheese Pizza",
    "Chicken Pizza",
    "Four Cheese Pizza",
    "Goat Cheese Pizza",
    "Grilled Pizza",
    "Hawaiian Pizza",
    "Margherita Pizza",
    "Mozzarella Pizza",
    "Mushroom Pizza",
    "Napoli Pizza",
    "New York Style Pizza",
    "Pepperoni Pizza",
    "Pizza Dough",
    "Pizza Rolls",
    "Quattro Formaggi Pizza",
    "Red Pepper Pizza",
    "Salami Pizza",
    "Sausage Pizza",
    "Seafood Pizza",
    "Shrimp Pizza",
    "Sicilian Pizza",
    "Spinach Feta Pizza",
    "Spinach Pizza",
    "Stuffed Crust Pizza",
    "Tarte Flambée",
    "Thin Crust Pizza",
    "Tuna Pizza",
    "Vegetable Pizza",
    "Vegetarian Pizza",
    "Veggie Pizza",
    "White Pizza",
    "American Cheese",
    "Applewood",
    "Asiago Cheese",
    "Babybel",
    "Blue Cheese",
    "Brie",
    "Camembert",
    "Cheddar",
    "Cheese Fondue",
    "Cheese Spread",
    "Cheese Whiz",
    "Chester",
    "Colby Cheese",
    "Colby-Jack Cheese",
    "Cottage Cheese",
    "Dutch Cheese",
    "Edam Cheese",
    "Emmentaler",
    "Feta",
    "Fontina",
    "Fresh Mozzarella",
    "Goat Cheese",
    "Gorgonzola",
    "Gouda",
    "Grated Parmesan",
    "Grilled Cheese",
    "Gruyere",
    "Halloumi",
    "Havarti",
    "Italian Cheese",
    "Jarlsberg",
    "Manchego Cheese",
    "Monterey",
    "Monterey Jack Cheese",
    "Mozzarella",
    "Muenster Cheese",
    "Neufchatel",
    "Parmesan",
    "Pecorino",
    "Provolone",
    "Raclette Cheese",
    "Ricotta",
    "White Cheddar",
    "Wisconsin Cheese",
    "Chive Cream Cheese",
    "Cottage Cheese",
    "Cream Cheese",
    "Cream Cheese with Herbs",
    "Feta Cream Cheese",
    "Garlic Cream Cheese",
    "Goat Cheese",
    "Horseradish",
    "Mascarpone",
    "Obatzda",
    "Olive Cream Cheese",
    "Pesto Cream Cheese",
    "Philadelphia Cream Cheese",
    "Pineapple Cream Cheese",
    "Salmon Cream Cheese",
    "Vegetable Cream Cheese",
    "Walnut Cream Cheese",
    "Almond Milk",
    "Buttermilk",
    "Chocolate Mousse",
    "Coconut Milk",
    "Coffee Creamer",
    "Condensed Milk",
    "Cottage Cheese",
    "Cream",
    "Creme Fraiche",
    "Custard",
    "Evaporated Milk",
    "Goat Milk",
    "Hot Chocolate",
    "Kefir",
    "Lactose-free Milk",
    "Lassi",
    "Milk",
    "Plain Yogurt",
    "Powdered Milk",
    "Quark",
    "Rice Milk",
    "Rice Pudding",
    "Semi-skimmed Milk",
    "Semolina Pudding",
    "Skim Milk",
    "Sour Cream",
    "Soy Milk",
    "Sweetened Condensed Milk",
    "Tzatziki",
    "Whipped Cream",
    "Whole Milk",
    "Yogurt",
    "American Cheese",
    "Applewood",
    "Bergkäse",
    "Butter Cheese",
    "Cheddar",
    "Cheese Platter",
    "Cheese Slices",
    "Edam",
    "Edam Cheese",
    "Emmental",
    "Emmentaler",
    "Fresh Mozzarella",
    "Gouda",
    "Gouda Cheese",
    "Havarti",
    "Leerdammer",
    "Leerdammer Cheese",
    "Maasdam Cheese",
    "Monterey Jack Cheese",
    "Mozzarella",
    "Muenster Cheese",
    "Pepper Cheese",
    "Sandwich Cheese",
    "Smoked Cheese",
    "Tilsit",
    "White American",
    "White Cheddar",
    "Young Gouda",
    "Aloe Vera Yogurt",
    "Ayran",
    "Bircher Muesli Yogurt",
    "Blueberry Yogurt",
    "Cherry Yogurt",
    "Chocolate Yogurt",
    "Cream Yogurt",
    "Creamy Yogurt",
    "Diet Yogurt",
    "Fruit Yogurt",
    "Greek Yogurt",
    "Low-Fat Yogurt",
    "Mocca Yogurt",
    "Organic Yogurt",
    "Peach Yogurt",
    "Plain Yogurt",
    "Probiotic Yogurt",
    "Skim Milk Yogurt",
    "Stracciatella Yogurt",
    "Strawberry Yogurt",
    "Vanilla Yogurt",
    "Yogurt",
    "Yogurt Corner",
    "Beef",
    "Beef Brisket",
    "Beef Fillet",
    "Beef Goulash",
    "Beef Minute Steak",
    "Beef Neck",
    "Beef Pancreas",
    "Beef Patty",
    "Beef Prime Rib",
    "Beef Ribs",
    "Beef Sirloin",
    "Beef Suet",
    "Beef Tallow",
    "Beef Thymus",
    "Beef Tripe",
    "Chuck Roast",
    "Chuck Steak",
    "Filet Mignon",
    "Flank Steak",
    "Ground Beef",
    "Ground Chuck",
    "Ground Round",
    "Minced Veal",
    "Porterhouse Steak",
    "Rib Eye Steak",
    "Roast Beef",
    "Rump Steak",
    "Skirt Steak",
    "Stew Beef",
    "Strip Steak",
    "T-Bone-Steak",
    "Veal",
    "Veal Breast",
    "Veal Leg",
    "Veal Roast Beef",
    "Veal Shank",
    "Veal Shoulder",
    "Veal Sirloin",
    "Veal Tenderloin",
    "Baked Ham",
    "Beef Salami",
    "Boiled Ham",
    "Bologna",
    "Bresaola",
    "Capicola",
    "Chicken Breast Fillet",
    "Chopped Ham",
    "Chorizo",
    "Corned Beef",
    "Dutch Loaf",
    "Ham",
    "Ham Sausage",
    "Head Cheese",
    "Hickory Ham",
    "Honey Ham",
    "Liverwurst",
    "Olive Loaf",
    "Oven-Roasted Turkey Breast",
    "Parma Ham",
    "Pastrami",
    "Pepperoni",
    "Pimento Loaf",
    "Pork Roast",
    "Prosciutto",
    "Roast Beef",
    "Salami",
    "Serrano Ham",
    "Smoked Ham",
    "Smoked Turkey Breast",
    "Summer Sausage",
    "Turkey Breast",
    "Turkey Ham",
    "Turkey Salami",
    "Beef",
    "Beef Brisket",
    "Beef Jerky",
    "Beef Ribs",
    "Beef Tenderloin",
    "Chicken",
    "Chicken Breast",
    "Chicken Drumstick",
    "Chicken Fat",
    "Chicken Giblets",
    "Chicken Gizzards",
    "Chicken Leg",
    "Chicken Liver",
    "Chicken Meat",
    "Chicken Thigh",
    "Chicken Wing",
    "Chuck Steak",
    "Cubed Steak",
    "Duck",
    "Filet Mignon",
    "Flank Steak",
    "Flat Iron Steak",
    "Ground Beef",
    "Ground Round",
    "Ham",
    "New York Strip Steak",
    "Ostrich",
    "Pork",
    "Pork Baby Back Ribs",
    "Pork Chops",
    "Pork Country-Style Ribs",
    "Pork Loin",
    "Pork Roast",
    "Pork Steaks",
    "Roast Beef",
    "Round Steak",
    "Schnitzel",
    "Spare Ribs",
    "Standing Rib Roast",
    "T-Bone Steak",
    "Turkey",
    "Turkey Breast",
    "Turkey Legs",
    "Turkey Steak",
    "Turkey Wings",
    "Chicken Giblets",
    "Chicken Heart",
    "Chicken Liver",
    "Chicken Stomach",
    "Chitterlings",
    "Duck Liver",
    "Goose Liver",
    "Hog Maws",
    "Pig Heart",
    "Pig Kidney",
    "Pork Liver",
    "Pork Melt",
    "Pork Tongue",
    "Turkey Giblets",
    "Turkey Heart",
    "Turkey Liver",
    "Veal Heart",
    "Veal Kidney",
    "Veal Tongue",
    "Bacon",
    "Brawn",
    "Canadian-Style Bacon",
    "Chitterlings",
    "Ground Pork",
    "Hog Maws",
    "Lard",
    "Meatloaf",
    "Parma Ham",
    "Pig Ear",
    "Pig Fat",
    "Pork Bacon",
    "Pork Belly",
    "Pork Blade Steak",
    "Pork Chop",
    "Pork Country-Style Ribs",
    "Pork Crown Roast",
    "Pork Cutlet",
    "Pork Cutlets",
    "Pork Leg",
    "Pork Loin",
    "Pork Meatloaf",
    "Pork Ragout",
    "Pork Rib Roast",
    "Pork Ribs",
    "Pork Roast",
    "Pork Sausage",
    "Pork Shank",
    "Pork Shoulder",
    "Pork Shoulder Blade",
    "Pork Stomach",
    "Rack of Pork",
    "Salt Meat",
    "Salt Pork",
    "Serrano Ham",
    "Spare Ribs",
    "Spareribs",
    "Capon",
    "Chicken",
    "Chicken Breast",
    "Chicken Drumsticks",
    "Chicken Gizzards",
    "Chicken Legs",
    "Chicken Thighs",
    "Chicken Wings",
    "Duck",
    "Duck Breast",
    "Emu",
    "Goose",
    "Guinea-Fowl",
    "Ostrich",
    "Ostrich Meat",
    "Pheasant",
    "Pheasant Breast",
    "Pheasant Leg",
    "Pigeon",
    "Poularde",
    "Rhea",
    "Turkey",
    "Turkey Breast",
    "Turkey Cutlet",
    "Turkey Drumsticks",
    "Turkey Legs",
    "Turkey Steak",
    "Turkey Wings",
    "Wild Duck",
    "Andouille",
    "Bacon",
    "Black Pudding",
    "Blood Sausage",
    "Bockwurst",
    "Boiled Ham",
    "Bologna",
    "Boudin",
    "Bratwurst",
    "Brawn",
    "Breakfast Sausage Links",
    "Cheese Pastry",
    "Chicken Breast",
    "Chicken Meat",
    "Chicken Salad",
    "Chorizo",
    "Cooked Ham",
    "Corned Beef",
    "Cumberland Sausage",
    "Frankfurters",
    "Garlic Sausage",
    "Hot Dogs",
    "Hot Sausage",
    "Italian Sausage",
    "Jerky",
    "Kielbasa",
    "Knackwurst",
    "Landjaeger",
    "Linguica",
    "Liver Pate",
    "Liverwurst",
    "Luncheon Meat",
    "Mettwurst",
    "Mortadella",
    "Pastrami",
    "Pepperoni",
    "Polish Sausage",
    "Pork",
    "Pork Roll",
    "Prosciutto",
    "Ring Bologna",
    "Salami",
    "Sausage",
    "Smoked Sausage",
    "Souse",
    "Spam",
    "Weisswurst",
    "Alligator",
    "Alligator Meat",
    "Antelope Meat",
    "Bear Meat",
    "Beaver Meat",
    "Bison",
    "Bison Meat",
    "Bison Sirloin",
    "Buffalo",
    "Buffalo Meat",
    "Caribou",
    "Goose",
    "Goose Meat",
    "Lamb",
    "Lamb Meat",
    "Mallard Duck Meat",
    "Mallard Meat",
    "Moose",
    "Moose Meat",
    "Mutton",
    "Mutton Meat",
    "Ostrich",
    "Ostrich Meat",
    "Pheasant",
    "Pheasant Meat",
    "Rabbit",
    "Reindeer",
    "Reindeer Meat",
    "Venison",
    "Venison Sirloin",
    "Wild Boar",
    "Wild Boar Meat",
    "Apple Cake",
    "Apple Cobbler",
    "Apple Crisp",
    "Apple Crumble",
    "Apple Pie",
    "Apple Strudel",
    "Apple Turnover",
    "Applesauce Cake",
    "Baked Alaska",
    "Bakewell Tart",
    "Banoffee Pie",
    "Black and White Cookie",
    "Black Forest Cake",
    "Blueberry Cobbler",
    "Blueberry Muffin",
    "Blueberry Pie",
    "Bundt Cake",
    "Buttermilk Pie",
    "Caramel Cake",
    "Carrot Cake",
    "Cheesecake",
    "Cherry Pie",
    "Chess Pie",
    "Chocolate Cake",
    "Chocolate Cream Pie",
    "Chocolate Mousse Cake",
    "Chocolate Mousse Pie",
    "Chocolate Muffin",
    "Coconut Cake",
    "Coffee Cake",
    "Cream Puff",
    "Crumb Cake",
    "Cupcake",
    "Danish Pastry",
    "Donut",
    "Doughnut",
    "Flan",
    "Flourless Chocolate Cake",
    "French Cruller",
    "Fruit Cake",
    "Funnel Cake",
    "German Chocolate Cake",
    "Gingerbread",
    "Ice Cream Cake",
    "Key Lime Pie",
    "King Cake",
    "Layer Cake",
    "Lemon Cake",
    "Lemon Meringue Pie",
    "Madeira Cake",
    "Marble Cake",
    "Meringue",
    "Opera Cake",
    "Paczki",
    "Pancake",
    "Panettone",
    "Pavlova",
    "Peach Cobbler",
    "Peach Pie",
    "Pecan Pie",
    "Pineapple Upside-Down Cake",
    "Plum Cake",
    "Poppy-Seed Cake",
    "Pound Cake",
    "Profiterole",
    "Puff Pastry",
    "Pumpkin Bread",
    "Pumpkin Cheesecake",
    "Pumpkin Pie",
    "Raspberry Pie",
    "Red Velvet Cake",
    "Rhubarb Pie",
    "Rum Cake",
    "Sacher Torte",
    "Sponge Cake",
    "Strawberry Cheesecake",
    "Strawberry Pie",
    "Strawberry Rhubarb Pie",
    "Sweet Potato Pie",
    "Swiss Roll",
    "Tarte Tatin",
    "Tiramisu",
    "Tiramisu Cake",
    "Treacle Tart",
    "Tres Leches Cake",
    "Trifle",
    "Victoria Sponge Cake",
    "Waffles",
    "Wedding Cake",
    "After Eight",
    "Airheads",
    "Almond Roca",
    "Angel Delight",
    "Animal Crackers",
    "Baby Ruth",
    "Butterfinger",
    "Buttermilk Pancakes",
    "Candy Apple",
    "Candy Cane",
    "Candy canes",
    "Candy Corn",
    "Candy Floss",
    "Caramel Popcorn",
    "Caramel squares",
    "Chocolate",
    "Chocolate Bar",
    "Chocolate Chips",
    "Cookies",
    "Cotton Candy",
    "Eggy Bread",
    "Fairy Cakes",
    "Ferrero Rocher",
    "Flapjack",
    "Fortune Cookies",
    "Granola Bars",
    "Gumdrops",
    "Gummi Bears",
    "Hanuta",
    "Hershey Kisses",
    "Jelly Beans",
    "Jelly Belly",
    "Jolly Ranchers",
    "Jordan Almonds",
    "Kit Kat",
    "Laffy Taffy",
    "Licorice",
    "LifeSavers",
    "Lindt Chocolate",
    "Liquorice",
    "Lollipop",
    "M&M’s",
    "Maltesers",
    "Mars Bar",
    "Marshmallows",
    "Marzipan",
    "Mike and Ike",
    "Milk Duds",
    "Milky Way",
    "PayDay",
    "Peanut Bar",
    "Peanut Brittle",
    "Peanut Butter Bars",
    "Peanut Butter Cookies",
    "Peppermint bark",
    "Pez",
    "Pop Rocks",
    "Popcorn",
    "Pumpkin Seeds",
    "Reeses Peanut Butter Cups",
    "Rice Pudding",
    "Roasted Almonds",
    "Rolo",
    "Semolina",
    "Skittles",
    "Smarties",
    "Smores",
    "Snickers",
    "Sour Patch Kids",
    "Speculoos",
    "Spritz Cookies",
    "Take 5",
    "Toblerone",
    "Trifle",
    "Twix",
    "Waffles",
    "Whoopie Pie",
    "Baskin-Robbins",
    "Ben and Jerry’s",
    "Butter Pecan Ice Cream",
    "Carvel",
    "Chocolate Chip Ice Cream",
    "Chocolate Ice Cream",
    "Ciao Bella",
    "Coffee Ice Cream",
    "Cold Stone Creamery",
    "Cookie Dough Ice Cream",
    "Crunchie McFlurry",
    "Dairy Milk McFlurry",
    "Dippin Dots",
    "Double Rainbow",
    "Drumsticks",
    "French Vanilla Ice Cream",
    "Healthy Choice",
    "Hot Fudge Sundae",
    "Ice Cream Sandwich",
    "Ice Cream Sundae",
    "Ice Milk",
    "Magnolia",
    "Magnum",
    "Magnum Almond",
    "Magnum Double Caramel",
    "Magnum Double Chocolate",
    "Magnum Gold",
    "Magnum White",
    "McFlurry",
    "McFlurry Oreo",
    "Mini Milk",
    "Mint Chocolate Chip Ice Cream",
    "Rocky Road Ice Cream",
    "Schwan’s",
    "Smarties McFlurry",
    "Snickers Ice Cream",
    "Soft Serve",
    "Solero",
    "Strawberry Ice Cream",
    "Strawberry Sundae",
    "Sundae",
    "Turkey Hill",
    "Vanilla Cone",
    "Vanilla Ice Cream",
    "Acai Juice",
    "Aloe Vera",
    "Apple Juice",
    "Apricot Nectar",
    "Banana Juice",
    "Blackberry Juice",
    "Boysenberry Juice",
    "Capri-Sun",
    "Carrot Juice",
    "Chamomile Tea",
    "Cherry Juice",
    "Clamato",
    "Coconut Milk",
    "Coconut Water",
    "Concord Grape",
    "Cranberry Apple Juice",
    "Cranberry Grape Juice",
    "Cranberry Juice",
    "Cucumber Juice",
    "Currant Juice",
    "Energy-Drink",
    "Fruitopia",
    "Grape Juice",
    "Grapefruit Juice",
    "Lemon Juice",
    "Lemonade",
    "Lime Juice",
    "Limeade",
    "Mango Lassi",
    "Nestea",
    "Orange Juice",
    "Papaya Juice",
    "Passion Fruit Juice",
    "Peach Juice",
    "Peach Nectar",
    "Pear Juice",
    "Pear Nectar",
    "Pineapple Juice",
    "Pineapple Orange Juice",
    "Plum Juice",
    "Pomegranate Juice",
    "Sauerkraut Juice",
    "Tangerine Juice",
    "Tomato Juice",
    "Vegetable Juice",
    "White Grape Juice",
    "Absinthe",
    "Advocaat",
    "Amaretto",
    "Applejack",
    "Asti",
    "Bailey’s Irish Cream",
    "Baileys",
    "Beer",
    "Blue Curacao",
    "Bourbon",
    "Brandy",
    "Canadian Whiskey",
    "Chambord",
    "Champagne",
    "Cider",
    "Cognac",
    "Cointreau",
    "Drambuie",
    "Frangelico",
    "Gin",
    "Glenfiddich",
    "Grand Marnier",
    "Irish Whiskey",
    "Jack Daniel’s",
    "Jagermeister",
    "Jim Beam",
    "Kahlua",
    "Liqueur",
    "Liquor",
    "Midori",
    "Prosecco",
    "Punch",
    "Red Wine",
    "Rose Wine",
    "Rum",
    "Sambuca",
    "Sangria",
    "Scotch",
    "Sherry",
    "Sloe Gin",
    "Southern Comfort",
    "Tequila",
    "Triple Sec",
    "Vermouth",
    "Vodka",
    "Whisky",
    "White Wine",
    "Wine",
    "Ale",
    "Altbier",
    "Bass",
    "Beck’s",
    "Beer",
    "Blue Moon",
    "Bock Beer",
    "Buckler (N.A.)",
    "Bud Ice",
    "Bud Light",
    "Bud Light Chelada",
    "Bud Light Lime",
    "Bud Select",
    "Bud Select 55",
    "Budweiser",
    "Budweiser Chelada",
    "Busch",
    "Busch Light",
    "Busch N.A.",
    "Carlsberg",
    "Clausthaler (N.A.)",
    "Colt 45",
    "Coors",
    "Coors Light",
    "Coors N.A.",
    "Corona",
    "Dark Beer",
    "Genesee Cream Ale",
    "Ginger Beer",
    "Guinness",
    "Heineken",
    "Honey Brown",
    "Hurricane High Gravity",
    "IPA",
    "Keystone Ice",
    "Keystone Light",
    "Koelsch",
    "Labatt",
    "Lager Beer",
    "Land Shark",
    "Light Beer",
    "Lowenbrau",
    "Malt Beer",
    "Michelob Amber Bock",
    "Michelob Lager",
    "Michelob Light",
    "Michelob Ultra",
    "Michelob Ultra Amber",
    "Michelob Ultra Lime Cactus",
    "Miller Chill",
    "Miller Genuine Draft",
    "Miller High Life",
    "Miller High Life Light",
    "Miller Lite",
    "Milwaukee’s Best",
    "Milwaukee’s Best Light",
    "Molson",
    "Natural Ice",
    "Natural Light",
    "Newcastle",
    "Non-alcoholic Beer",
    "O’Doul’s (N.A.)",
    "Old Milwaukee",
    "Old Milwaukee N.A.",
    "Olde English",
    "Pabst Blue Ribbon",
    "Pale Ale",
    "Pilsner",
    "Porter",
    "Redbridge (Gluten-free)",
    "Rolling Rock",
    "Rolling Rock Light",
    "Root Beer",
    "Samuel Adams",
    "Shock Top",
    "Shock Top Raspberry Wheat",
    "Sierra Nevada Strong",
    "Sparks",
    "St. Pauli Girl",
    "Steel Reserve",
    "Stout",
    "Stout Beer",
    "Strong Beer",
    "Tilt",
    "Wheat Beer",
    "ACE Drink",
    "Apple Spritzer",
    "Chai",
    "Chai Tea",
    "Chocolate Milk",
    "Chocolate Milkshake",
    "Club Mate",
    "Coca Cola",
    "Coffee",
    "Coke Zero",
    "Cola",
    "Crystal Light",
    "Diet Coke",
    "Egg Cream",
    "Egg Nog",
    "Elderflower Cordial",
    "Evian",
    "Gatorade",
    "Ginger Tea",
    "Hawaiian Punch",
    "Hi-C",
    "Horchata",
    "Hot Chocolate",
    "Ice Tea",
    "Iced Tea",
    "Karamalz",
    "Kombucha",
    "Kool-Aid",
    "Lassi",
    "Latte Macchiato",
    "Lemonade",
    "Malt Beer",
    "Milk",
    "Milkshake (dry)",
    "Milo",
    "Nectar",
    "Nestea",
    "Non-alcoholic Beer",
    "Powerade",
    "Slurpee",
    "Slush Puppie",
    "Smoothie",
    "Soy Milk",
    "Strawberry Milkshake",
    "Tang",
    "Tap Water",
    "Tea",
    "Vanilla Milkshake",
    "Volvic",
    "Water",
    "Yerba Mate",
    "7up",
    "Barq’s",
    "Bitter Lemon",
    "Canada Dry Ginger Ale",
    "Cherry Coke",
    "Coke",
    "Coke Zero",
    "Diet Cherry Coke",
    "Diet Coke",
    "Diet Dr. Pepper",
    "Diet Pepsi",
    "Diet Sunkist",
    "Dr. Brown’s",
    "Dr. Pepper",
    "Fanta",
    "Fanta Zero",
    "Five Alive",
    "Fresca",
    "Full Throttle",
    "Fuze",
    "Fuze Tea",
    "Gatorade",
    "Ginger Ale",
    "Ice Tea",
    "Jolt Cola",
    "Kool-Aid",
    "Lemonade",
    "Mello Yello",
    "Minute Maid",
    "Minute Maid Light",
    "Mug Root Beer",
    "Orange Soda",
    "Pepsi",
    "Pibb Xtra",
    "Powerade",
    "Schweppes Ginger Ale",
    "Soda",
    "Sprite",
    "Sprite Zero",
    "Squirt",
    "Sunkist",
    "Surge",
    "TaB",
    "Tonic Water",
    "Vanilla Coke",
    "Cabernet Sauvignon",
    "Cava",
    "Champagne",
    "Chardonnay",
    "Chenin Blanc",
    "Chocolate Wine",
    "Dry Red Wine",
    "Gamay",
    "Malbec",
    "Malbec Wine",
    "Marsala Wine",
    "Merlot",
    "Merlot Wine",
    "Moscato Wine",
    "Mulled Wine",
    "Pinot Gris",
    "Pinot Noir",
    "Plum Wine",
    "Port Wine",
    "Prosecco",
    "Red Wine",
    "Red Wines",
    "Riesling",
    "Riesling Wine",
    "Rose Wine",
    "Sangria",
    "Sauvignon Blanc",
    "Sherry",
    "Shiraz",
    "Sparkling Wine",
    "Sweet Red Wine",
    "Sweet White Wine",
    "Sweet Wines",
    "Vermouth",
    "White Wine",
    "White Zinfandel",
    "Wine",
    "Yellow Tail Wine",
    "Zinfandel",
    "Amaranth",
    "Barley",
    "Barley Groats",
    "Brown Rice",
    "Buckwheat",
    "Buckwheat Groats",
    "Corn Waffles",
    "Cornmeal",
    "Cornstarch",
    "Couscous",
    "Cracker",
    "Durum Wheat Semolina",
    "Flaxseed",
    "Freekeh",
    "Gluten",
    "Grissini",
    "Kamut",
    "Millet",
    "Millet Flour",
    "Millet Gruel",
    "Oat Bran",
    "Pearl Barley",
    "Polenta",
    "Prawn Crackers",
    "Pretzel Sticks",
    "Quinoa",
    "Rusk",
    "Rye Bran",
    "Sago",
    "Savoury Biscuits",
    "Shortbread",
    "Spelt",
    "Spelt Bran",
    "Spelt Semolina",
    "Sunflower Seeds",
    "Tortilla",
    "Tortilla Chips",
    "Wheat Bran",
    "Wheat Germ",
    "Wheat Gluten",
    "Wheat Semolina",
    "Wheat Starch",
    "Whole Grain Wheat",
    "Wholegrain Oat",
    "Bran Flakes",
    "Cheerios",
    "Chex",
    "Chocolate Cheerios",
    "Chocos",
    "Cinnamon Toast Crunch",
    "Coco Pops",
    "Cocoa Krispies",
    "Cocoa Pebbles",
    "Cocoa Puffs",
    "Cookie Crisp",
    "Corn Flakes",
    "Corn Pops",
    "Count Chocula",
    "Cracklin Oat Bran",
    "Cream of Wheat",
    "Crunchy Nut",
    "Crunchy Nut Cornflakes",
    "Fiber One",
    "Froot Loops",
    "Frosted Cheerios",
    "Frosted Flakes",
    "Frosted Mini-Wheats",
    "Frosties",
    "Fruity Pebbles",
    "Golden Grahams",
    "Grape-Nuts",
    "Honey Nut Cheerios",
    "Honey Smacks",
    "Honeycomb",
    "Just Right",
    "Kashi",
    "Kelloggs Corn Flakes",
    "Kix",
    "Krave",
    "Life Cereal",
    "Lucky Charms",
    "Malt-O-Meal",
    "Mini-Wheats",
    "Muesli",
    "Multigrain Cheerios",
    "Nutri-Grain",
    "Oatibix",
    "Oatmeal",
    "Peanut Butter Toast Crunch",
    "Post Raisin Bran",
    "Post Shredded Wheat",
    "Puff",
    "Puffed Rice",
    "Puffed Wheat",
    "Quaker Grits",
    "Quaker Oatmeal",
    "Quaker Oatmeal Squares",
    "Raisin Bran",
    "Raisin Bran Crunch",
    "Raisin Bran Crunch",
    "Raisin Nut Bran",
    "Ready Brek",
    "Rice Chex",
    "Rice Krispies",
    "Scooters",
    "Shredded Wheat",
    "Shreddies",
    "Smart Start",
    "Special K",
    "Special K Chocolatey Delight",
    "Special K Protein Plus",
    "Special K Red Berries",
    "Sugar Puffs",
    "Toasties",
    "Trix",
    "Weet-Bix",
    "Weetabix",
    "Weetos",
    "Wheaties",
    "Cannelloni",
    "Capellini",
    "Cappelletti",
    "Cellophane Noodles",
    "Cheese Tortellini",
    "Dampfnudel",
    "Dumpling Dough",
    "Durum Wheat Semolina",
    "Egg Noodles",
    "Farfalle",
    "Fettuccine",
    "Fusilli",
    "Glass Noodles",
    "Lasagne Sheets",
    "Linguine",
    "Low Carb Pasta",
    "Macaroni",
    "Manicotti",
    "Mostaccioli",
    "Orecchiette",
    "Orzo",
    "Penne",
    "Penne Rigate",
    "Pierogi",
    "Ravioli",
    "Rigatoni",
    "Rotini",
    "Shells",
    "Shirataki Noodles",
    "Soy Noodles",
    "Spaetzle",
    "Spaghetti",
    "Spinach Tortellini",
    "Spirelli",
    "Tagliatelle",
    "Tortellini",
    "Vermicelli",
    "Whole Grain Noodles",
    "Whole Grain Spaghetti",
    "Ziti",
    "Baby Back Ribs",
    "Bacon and Eggs",
    "Baked Beans",
    "Baked Chicken",
    "BBQ Ribs",
    "Beef Stew",
    "Biryani",
    "Black Pudding",
    "Black Rice",
    "BLT",
    "Brown Rice",
    "Burrito",
    "Butter Chicken",
    "California Roll",
    "Chicken Caesar Salad",
    "Chicken Fried Steak",
    "Chicken Marsala",
    "Chicken Parmesan",
    "Chicken Pot Pie",
    "Chicken Tikka Masala",
    "Chili con Carne",
    "Chimichanga",
    "Cobb Salad",
    "Collard Greens",
    "Corn Dog",
    "Corned Beef Hash",
    "Cottage Pie",
    "Dal",
    "Deviled Eggs",
    "Dim Sum",
    "Dosa",
    "Enchiladas",
    "Fajita",
    "Fish and Chips",
    "Fried Rice",
    "Fried Shrimp",
    "Grilled Cheese Sandwich",
    "Ham and Cheese Sandwich",
    "Hummus",
    "Jambalaya",
    "Kebab",
    "Lasagne",
    "Mac and Cheese",
    "Macaroni and Cheese",
    "Mashed Potatoes",
    "Meat Pie",
    "Meatloaf",
    "Naan",
    "Orange Chicken",
    "Pad Thai",
    "Paella",
    "Paratha",
    "Pea Soup",
    "Peanut Butter Sandwich",
    "Peking Duck",
    "Philly Cheese Steak",
    "Pizza",
    "Pork Chop",
    "Potato Salad",
    "Pulled Pork Sandwich",
    "Ramen",
    "Ravioli",
    "Reuben Sandwich",
    "Roast Beef",
    "Roast Dinner",
    "Samosa",
    "Sausage Roll",
    "Sausage Rolls",
    "Shepherds Pie",
    "Shrimp Cocktail",
    "Sloppy Joe",
    "Sloppy Joes",
    "Spaghetti Bolognese",
    "Spring Roll",
    "Spring Rolls",
    "Taco",
    "Tandoori Chicken",
    "Yorkshire Pudding",
    "Alphabet Soup",
    "Bean Stew",
    "Beef Bouillon",
    "Beef Noodle Soup",
    "Beef Soup",
    "Bouillon",
    "Broccoli Cheese Soup",
    "Broccoli Soup",
    "Cabbage Soup",
    "Carrot Ginger Soup",
    "Carrot Soup",
    "Chicken Bouillon",
    "Chicken Broth",
    "Chicken Gumbo Soup",
    "Chicken Noodle Soup",
    "Chicken Stock",
    "Chicken Vegetable Soup",
    "Chicken with Rice Soup",
    "Cream of Asparagus Soup",
    "Cream of Broccoli Soup",
    "Cream of Celery Soup",
    "Cream of Chicken Soup",
    "Cream of Mushroom Soup",
    "Cream of Onion Soup",
    "Cream of Potato Soup",
    "Creamy Chicken Noodle Soup",
    "French Onion Soup",
    "Golden Mushroom Soup",
    "Goulash",
    "Instant Ramen",
    "Lentil Soup",
    "Lobster Bisque Soup",
    "Meatball Soup",
    "Minestrone",
    "Mushroom Soup",
    "Noodle Soup",
    "Onion Soup",
    "Oxtail Soup",
    "Pea Soup",
    "Potato Soup",
    "Pumpkin Soup",
    "Ramen",
    "Scotch Broth",
    "Succotash",
    "Thai Soup",
    "Tomato Rice Soup",
    "Tomato Soup",
    "Vegetable Beef Soup",
    "Vegetable Broth",
    "Vegetable Soup",
    "Vegetable Stock",
    "Wedding Soup",
    "Azuki Bean",
    "Bamboo Shoots",
    "Bean Curd",
    "Bean Sprouts",
    "Bengal Gram",
    "Black Beans",
    "Black Chickpeas",
    "Black Gram",
    "Brown Lentil",
    "Butternut",
    "Chickpeas",
    "Chili Bean",
    "Dal",
    "Deep-Fried Tofu",
    "Extra-Firm Tofu",
    "Firm Tofu",
    "Flageolet",
    "Fried Bean Curd",
    "Green Beans",
    "Green Gram",
    "Green Lentil",
    "Kidney Beans",
    "Lentils",
    "Lima Beans",
    "Marron",
    "Miso",
    "Mung Beans",
    "Natto",
    "Navy Bean",
    "Okara",
    "Okra",
    "Peanuts",
    "Peas",
    "Pecan",
    "Pinto Beans",
    "Puy Lentils",
    "Rajma",
    "Red Beans",
    "Red Kidney Bean",
    "Red Lentils",
    "Refried Beans",
    "Roasted Soybeans",
    "Silken Tofu",
    "Soft Tofu",
    "Soy Cheese",
    "Soy Mayonnaise",
    "Soy Nut Butter",
    "Soy Nuts",
    "Soy Yogurt",
    "Soya Cheese",
    "Soybeans",
    "Soynut Butter",
    "Sugar Peas",
    "Sweet Peas",
    "Tempeh",
    "Textured Soy Protein",
    "Textured Vegetable Protein",
    "Tofu",
    "White Beans",
    "Yam Bean",
    "Yellow Lentils",
    "Yuba",
    "Acorn",
    "Alfalfa Sprouts",
    "Almonds",
    "Beechnut",
    "Brazil Nuts",
    "Breadfruit",
    "Butternut",
    "Cashew",
    "Chestnut",
    "Chia Seeds",
    "Coconut",
    "Cotton Seeds",
    "Flaxseed",
    "Ginkgo Nuts",
    "Goa Bean",
    "Hazelnut",
    "Hickory Nuts",
    "Lima Beans",
    "Lotus Seed",
    "Macadamia Nuts",
    "Peanuts",
    "Peas",
    "Pecan Nuts",
    "Pecans",
    "Pili Nuts",
    "Pine Nuts",
    "Pinto Beans",
    "Pistachios",
    "Poppy Seeds",
    "Pumpkin Seeds",
    "Radish Seeds",
    "Safflower Seeds",
    "Sesame Seeds",
    "Smoked Almonds",
    "Soy Beans",
    "Sunflower Seeds",
    "Sweet Chestnut",
    "Walnuts",
    "Watermelon",
    "Almond Oil",
    "Avocado Oil",
    "Butter",
    "Canola Oil",
    "Coconut Oil",
    "Cod Liver Oil",
    "Corn Oil",
    "Cottonseed Oil",
    "Flaxseed Oil",
    "Ghee",
    "Goose Fat",
    "Grape Seed Oil",
    "Hemp Oil",
    "Herring Oil",
    "Lard",
    "Macadamia Oil",
    "Margarine",
    "Mustard Oil",
    "Olive Oil",
    "Palm Oil",
    "Peanut Oil",
    "Real Butter",
    "Rice Bran Oil",
    "Safflower Oil",
    "Sardine Oil",
    "Sesame Oil",
    "Soybean Oil",
    "Sunflower Oil",
    "Walnut Oil",
    "Almond Oil",
    "Apricot Kernel Oil",
    "Argan Oil",
    "Avocado Oil",
    "Babassu Oil",
    "Canola Oil",
    "Coconut Oil",
    "Corn Oil",
    "Cottonseed Oil",
    "Flaxseed Oil",
    "Grape Seed Oil",
    "Hazelnut Oil",
    "Linseed Oil",
    "Menhaden Oil",
    "Mustard Oil",
    "Oat Oil",
    "Olive Oil",
    "Palm Kernel Oil",
    "Palm Oil",
    "Peanut Oil",
    "Poppy Seed Oil",
    "Pumpkin Seed Oil",
    "Rice Bran Oil",
    "Safflower Oil",
    "Salmon Oil",
    "Sesame Oil",
    "Shea Oil",
    "Soy Oil",
    "Sunflower Oil",
    "Tomato Seed Oil",
    "Vegetable Oil",
    "Walnut Oil",
    "Wheat Germ Oil",
    "Agar-Agar",
    "Agave Syrup",
    "All Purpose Flour",
    "Almond Extract",
    "Almonds",
    "Apple Pie Filling",
    "Baking Powder",
    "Baking Soda",
    "Bread Flour",
    "Brittle",
    "Brown Sugar",
    "Buttermilk",
    "Butterscotch Chips",
    "Cake Flour",
    "Candied Orange Peel",
    "Cane Sugar",
    "Chocolate Chips",
    "Chocolate Sprinkles",
    "Cocoa Powder",
    "Coconut Flakes",
    "Coconut Milk",
    "Corn Flour",
    "Corn Syrup",
    "Cornmeal",
    "Cornstarch",
    "Couverture",
    "Cream Cheese",
    "Cream of Tartar",
    "Crystallized Ginger",
    "Custard Powder",
    "Dark Rum",
    "Dextrose",
    "Dried Apricots",
    "Dried Cranberries",
    "Dried Figs",
    "Dried Prunes",
    "Duck Egg",
    "Egg",
    "Egg Nog",
    "Egg White",
    "Egg Yolk",
    "Evaporated Milk",
    "Flour",
    "Fructose",
    "Gelatin",
    "Glucose",
    "Glucose Syrup",
    "Granulated Sugar",
    "Ground Cinnamon",
    "Hazelnuts",
    "Heavy Cream",
    "Jaggery",
    "Lemon Pie Filling",
    "Malt Powder",
    "Malted Milk",
    "Maltitol",
    "Maltodextrin",
    "Maltose",
    "Maple Syrup",
    "Molasses",
    "Nonpareils",
    "Peppermint Extract",
    "Poppy Seeds",
    "Powdered Milk",
    "Powdered Sugar",
    "Protein Powder",
    "Raisins",
    "Rice Milk",
    "Rock Sugar",
    "Rolled Oats",
    "Rum",
    "Semolina Flour",
    "Sesame Seeds",
    "Shredded Coconut",
    "Sorbitol",
    "Soy Milk",
    "Soy Protein Powder",
    "Sprinkles",
    "Starch",
    "Strawberry Preserves",
    "Sucrose",
    "Sugar",
    "Sunflower Seeds",
    "Sweetened Condensed Milk",
    "Sweetener",
    "Unsalted Butter",
    "Vanilla Extract",
    "Vanilla Sugar",
    "Vegetable Oil",
    "Vegetable Shortening",
    "Walnuts",
    "Whole Milk",
    "Whole Wheat Flour",
    "Yeast (dry)",
    "Anchovy",
    "Bluefish",
    "Bream",
    "Butterfish",
    "Calamari",
    "Carp",
    "Caviar",
    "Clam",
    "Cod",
    "Crawfish",
    "Crayfish",
    "Eel",
    "Fish Fingers",
    "Fish Sticks",
    "Flounder",
    "Grouper",
    "Haddock",
    "Hake",
    "Halibut",
    "Herring",
    "Hoki",
    "Kipper",
    "Ling",
    "Lobster",
    "Mackerel",
    "Milkfish",
    "Monkfish",
    "Mullet",
    "Mussel",
    "Octopus",
    "Pickerel",
    "Pickled Herring",
    "Pike",
    "Plaice",
    "Pollack",
    "Red Snapper",
    "Redfish",
    "Rollmops",
    "Salmon",
    "Sardines",
    "Scallops",
    "Scampi",
    "Sea Bass",
    "Shad",
    "Shark",
    "Smelt",
    "Sole",
    "Squid",
    "Sturgeon",
    "Sushi",
    "Swordfish",
    "Triggerfish",
    "Trout",
    "Tuna",
    "Tuna Salad",
    "Turbot",
    "Wahoo",
    "Whitefish",
    "Whiting",
    "Zander",
    "Almond Extract",
    "Anise",
    "Anise Seed",
    "Arrowroot",
    "Arugula",
    "Balsamic Vinegar",
    "Basil",
    "Black Pepper",
    "Black Sesame Seeds",
    "Broth",
    "Capers",
    "Caraway Seeds",
    "Cardamom",
    "Cassava",
    "Cayenne Pepper",
    "Chard",
    "Chicory Greens",
    "Chicory Roots",
    "Chili",
    "Chili Powder",
    "Chives",
    "Cider Vinegar",
    "Cilantro",
    "Cinnamon",
    "Cloves",
    "Coriander",
    "Cream of Tartar",
    "Cress",
    "Crystallized Ginger",
    "Cumin",
    "Cumin Seed",
    "Curry",
    "Dandelion",
    "Dill",
    "Dill Weed",
    "Fennel",
    "Fennel Seed",
    "Fenugreek",
    "Garlic",
    "Garlic Powder",
    "Garlic Salt",
    "Ginger",
    "Grape Leaves",
    "Ground Ginger",
    "Horseradish",
    "Hot Pepper",
    "Iodized Salt",
    "Jalapeno",
    "Juniper",
    "Lemon Grass",
    "Licorice",
    "Maggi",
    "Marjoram",
    "Minced Onion",
    "Mint",
    "Mustard Seed",
    "Nutmeg",
    "Okra",
    "Onion",
    "Onion Powder",
    "Orange Peel",
    "Oregano",
    "Paprika",
    "Parsley",
    "Parsnip",
    "Pepper",
    "Poppy Seed",
    "Poultry Seasoning",
    "Pumpkin Pie Spice",
    "Red Pepper",
    "Red Wine Vinegar",
    "Rosemary",
    "Saffron",
    "Sage",
    "Salt",
    "Savory",
    "Sea Salt",
    "Serrano Pepper",
    "Sesame Seeds",
    "Stevia",
    "Tamarind",
    "Taro",
    "Tarragon",
    "Thyme",
    "Turmeric",
    "Vanilla Bean",
    "Vanilla Extract",
    "Vinegar",
    "White Pepper",
    "Yam",
    "Apple Pie",
    "Apple Turnover",
    "Bagel",
    "Baguette",
    "Banana Bread",
    "Banana Nut Bread",
    "Beer Bread",
    "Biscuit",
    "Black Bread",
    "Bran Muffins",
    "Bread Pudding",
    "Breadsticks",
    "Brioche",
    "Brown Bread",
    "Brownies",
    "Bun",
    "Cannoli",
    "Caramel Cake",
    "Challah",
    "Chapati",
    "Ciabatta",
    "Cinnamon Bun",
    "Coffee Cake",
    "Conchas/Mexican Sweet Bread",
    "Cornbread",
    "Crepes",
    "Croissant",
    "Crumpet",
    "Cupcakes",
    "Donut/Doughnut",
    "Dosa",
    "Empanada",
    "English Muffin",
    "Flatbread",
    "Focaccia",
    "Garlic Bread",
    "Hot Dog Buns",
    "Italian Bread",
    "Latkes",
    "Matzo Bread",
    "Monkey Bread",
    "Muffin",
    "Multi-Grain Bread",
    "Naan",
    "Oatmeal Cookies",
    "Oatmeal Raisin Cookies",
    "Pan de Sal",
    "Pancake",
    "Pandesal",
    "Panettone",
    "Pide",
    "Pie",
    "Pita Bread",
    "Potato Bread",
    "Pretzel",
    "Pretzel Roll",
    "Puff Pastry",
    "Pumpernickel",
    "Raisin Bread",
    "Roll",
    "Roti",
    "Rye Bread",
    "Sandwich",
    "Sandwich Bread",
    "Scone",
    "Shortcrust Pastry",
    "Soda Bread",
    "Soufflé",
    "Sourdough Bread",
    "Spanakopita",
    "Spice Cake",
    "Sweet Rolls",
    "Swiss Roll",
    "Toast",
    "Tortilla",
    "Tortilla Bread",
    "White Bread",
    "Whole Wheat Bread",
    "1000 Island Dressing",
    "Ajvar",
    "Arrabiata Sauce",
    "Balsamic Vinaigrette Dressing",
    "Barbecue Sauce",
    "Bechamel Sauce",
    "Bernaise Sauce",
    "Blue Cheese Dressing",
    "Bolognese",
    "Buttermilk Ranch Dressing",
    "Caesar Dressing",
    "Catalina Dressing",
    "Chasseur Sauce",
    "Chili Sauce",
    "Cream Sauce",
    "Curry Ketchup",
    "Curry Sauce",
    "French Dressing",
    "Gravy",
    "Greek Dressing",
    "Hamburger Sauce",
    "Harissa",
    "Hollandaise Sauce",
    "Honey Mustard Dressing",
    "Horseradish",
    "Italian Dressing",
    "Ketchup",
    "Mayonnaise",
    "Mustard",
    "Mustard Sauce",
    "Orange Sauce",
    "Pesto",
    "Ranch Dressing",
    "Remoulade Sauce",
    "Russian Dressing",
    "Salad Dressing",
    "Sambal Oelek",
    "Sesame Ginger Dressing",
    "Sesame Paste",
    "Sour Cream",
    "Sour Cream Sauce",
    "Soy Sauce",
    "Sweet and Sour Sauce",
    "Tabasco",
    "Teriyaki Sauce",
    "Thai Curry Paste",
    "Tomato Paste",
    "Tomato Puree",
    "Tomato Sauce",
    "Tzatziki",
    "Vinaigrette",
    "Worcestershire Sauce",
    "Yogurt Dressing",
    "Zesty Italian Dressing",
    "Almond Butter",
    "Apple Butter",
    "Applesauce",
    "Apricot Jam",
    "Blackberry Jam",
    "Blackcurrant Jam",
    "Blueberry Jam",
    "Cheese Spread",
    "Cherry Jam",
    "Chocolate Philadelphia",
    "Chocolate Spread",
    "Cream Cheese",
    "Egg",
    "Grape Jelly",
    "Honey",
    "Jelly",
    "Jif Peanut Butter",
    "Liverwurst",
    "Margarine",
    "Marmite",
    "Marshmallow Fluff",
    "Nutella",
    "Olive Spread",
    "Pâté (720), Pate",
    "Peanut Butter",
    "Peter Pan Peanut Butter",
    "Philadelphia Cream Cheese",
    "Plum Jam",
    "Salted Butter",
    "Skippy Peanut Butter",
    "Smuckers Strawberry Jam",
    "Strawberry Jam",
    "Strawberry Jelly",
    "Sunbutter",
    "Sunflower Butter",
    "Tapenade",
    "Unsalted Butter",
    "Vegemite",
    "Wild Honey",
]

# items for exclusion from Vision API classifications
INVALID_ITEMS = [
    "Food",
    "Fried food",
    "Finger food",
    "Deep frying",
    "Delicacy",
    "Side dish",
    "Fast food restaurant",
    "Meal",
    "Slider",
    "appetizer",
    "Brunch",
    "Red cabbage",
    "Vegan nutrition",
    "Sweetness",
    "Sourness",
    "Bitterness",
    "Green",
    "Tableware",
    "Recipe",
    "Ingredient",
    "Fast food",
    "Fruit",
    "Staple food",
    "Cooking",
    "Kitchen",
    "Cookware and bakeware",
    "Baked goods",
    "Cuisine",
    "Dish",
    "Produce",
    "Comfort food",
    "Garnish",
    "Junk Food",
    "Take-out food",
    "Italian food",
    "Meat",
    "Vegetable",
    "Plate",
    "American Food",
    "Chinese Food",
    "Food additive",
    "Serveware",
    "Supper",
    "Lunch",
    "Breakfast",
    "Gluten",
    "art",
    "Indian cuisine",
    "Natural foods",
    "Baking",
    "Leaf vegetable",
    "American food",
]
